## Numpy

In [5]:
import numpy as np

In [6]:
liste1 = [1,2,3,4,5]

In [7]:
array1 = np.array([1,2,3,4,5])

In [8]:
liste1

[1, 2, 3, 4, 5]

In [9]:
array1

array([1, 2, 3, 4, 5])

In [10]:
vektor = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [12]:
vektor.shape

(12,)

In [15]:
vektor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
matris = vektor.reshape(4,3)

In [83]:
matris.ravel() # boyutu teke indirir.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
matris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#attribute

In [23]:
matris.shape

(4, 3)

In [24]:
matris.ndim

2

In [25]:
matris.dtype

dtype('int32')

In [26]:
matris.size

12

In [29]:
array2 = np.array([1,2,3,4,5,"a"]) # Arrayler içinde bir tane string değer olduğu için diğer değerlere de string gözüyle bakar.

In [30]:
array2.dtype

dtype('<U11')

#Özel Matrisler

In [32]:
sifir_matris = np.zeros((3,3))

In [33]:
sifir_matris

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# np.random --> bir modüldür. Modül demek içerisinde classlar ve fonksiyonlar barındıran üst başlıktır.

In [38]:
rastgele_matris = np.random.rand(3,4) # 0 ve 1 arasında rastgele sayı üretir.

In [39]:
rastgele_matris

array([[0.36834339, 0.3456722 , 0.18706453, 0.21227263],
       [0.70203305, 0.89591254, 0.96862888, 0.48236333],
       [0.61050664, 0.93682414, 0.8615288 , 0.17878594]])

In [42]:
lin_matrisi = np.linspace(0,10,5) # 0-10 arası eşit aralıklarla 5 sayı üretir.

In [43]:
lin_matrisi

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
tmatris = matris.T #Transpose işlemi

In [58]:
tmatris

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

#Dört İşlem

In [59]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [60]:
toplama = a + b

In [61]:
toplama

array([11, 22, 33])

In [62]:
çıkarma = a - b

In [63]:
çıkarma

array([ 9, 18, 27])

In [64]:
çarpma = a*b

In [65]:
çarpma

array([10, 40, 90])

In [66]:
bölme = a/b

In [67]:
bölme

array([10., 10., 10.])

In [68]:
matris.max()

12

In [69]:
matris.min()

1

In [70]:
matris.mean()

6.5

In [71]:
matris.sum()

78

In [77]:
# Özel fonksiyonun print fonksiyonu içinde kendi haliyle kullanılmasını istersek başına f koymalıyız.
# Kullanılacak fonkisyon süslü parantez haliyle yazılmalıdır. Buna f-string yazılımı denir.

In [78]:
print(f"Matrisin en büyük elemanı: {matris.max()}")

Matrisin en büyük elemanı: 12


In [79]:
matris[0,2]

3

In [81]:
matris[3:] # satırın hepsini getirir.

array([[10, 11, 12]])

In [82]:
matris[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [84]:
v1 = np.array([1,2])
v2 = np.array([3,4])

#Vektörlerde birleştirme

In [92]:
# Not: (v1,v2) yaptık v1,v2 demekdik çünkü açıklamasına baktığında bizden tuple bekliyor. Bu noktada açıklamalara ne kadar bakarsak o kadar az syntax hatası yaparız. 
yatayvector = np.hstack((v1,v2)) # yatayda birleştirme yapar.

In [93]:
yatayvector

array([1, 2, 3, 4])

In [94]:
dikeyvector = np.vstack((v1,v2)) # dikeyde birleştirme yapar.

In [95]:
dikeyvector

array([[1, 2],
       [3, 4]])

In [96]:
d = np.array([1,2,3])

In [97]:
e = d

In [98]:
d

array([1, 2, 3])

In [99]:
e

array([1, 2, 3])

In [100]:
e[0] = 50

In [101]:
e

array([50,  2,  3])

In [102]:
d

array([50,  2,  3])

In [103]:
# Yukarıda görüldüğü gibi e arrayinde yapılan değişiklikten d etkilendi. Bunun önüne geçmek için kopyasını almalıyız.

#Vektörden vektör türetmek

In [106]:
e = d.copy()

In [107]:
e

array([50,  2,  3])

## Pandas

In [139]:
import pandas as pd

In [140]:
seri = pd.Series(liste1)

In [141]:
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [142]:
harfler = pd.Series(["a","b","c"])

In [143]:
# DataFrame oluşturmak için birden fazla series yan yana gelir ya da dataFrame yapısı Python’daki dictionary’ye ya da Numpy’daki çok boyutlu arraylere benzediği için buradan türetebiliriz.

In [144]:
data = {
    "ad":["Aziz","Mehmet","Nadi","Bülent"],
    "şehir": ["İstanbul","Ankara","Bursa","Kocaeli"]
}

In [145]:
data

{'ad': ['Aziz', 'Mehmet', 'Nadi', 'Bülent'],
 'şehir': ['İstanbul', 'Ankara', 'Bursa', 'Kocaeli']}

In [146]:
df = pd.DataFrame(data) # dictionary'den dataframe ürettik.

In [147]:
df

ad     şehir
0    Aziz  İstanbul
1  Mehmet    Ankara
2    Nadi     Bursa
3  Bülent   Kocaeli

In [148]:
df.head() # İlk 5 satırı gösterir, içine hangi rakamı yazarsak o kadar gösterir.

ad     şehir
0    Aziz  İstanbul
1  Mehmet    Ankara
2    Nadi     Bursa
3  Bülent   Kocaeli

In [149]:
df.tail(2) # Sondaki satırları gösterir.

ad    şehir
2    Nadi    Bursa
3  Bülent  Kocaeli

In [150]:
df.sample(2) # dataframe içinden rastgele değer getirir.

ad     şehir
1  Mehmet    Ankara
0    Aziz  İstanbul

In [151]:
df.sample(2)

ad    şehir
1  Mehmet   Ankara
3  Bülent  Kocaeli

In [152]:
df.dtypes #veri tipi öğrenme

ad       object
şehir    object
dtype: object

In [153]:
df.columns

Index(['ad', 'şehir'], dtype='object')

#Dataframe'de işlem yapma

In [158]:
#Dataframelerde işlem yapmak için (insert,update) loc fonksiyonu kullanılır.

In [159]:
#DF'de update yapma
df.loc[df["ad"]=="Mehmet","şehir"] = "Denizli"

In [160]:
df

ad     şehir
0    Aziz  İstanbul
1  Mehmet   Denizli
2    Nadi     Bursa
3  Bülent   Kocaeli

In [163]:
#DF'de insert yapma
df.loc[4] = ["İlknur","Sivas"] # Df'de 4. satır olmadığı için 4 seçtik.

In [162]:
df

ad     şehir
0    Aziz  İstanbul
1  Mehmet   Denizli
2    Nadi     Bursa
3  Bülent   Kocaeli
4  İlknur     Sivas

In [164]:
df.loc[5] = ["Harun","Konya"]

In [165]:
df

ad     şehir
0    Aziz  İstanbul
1  Mehmet   Denizli
2    Nadi     Bursa
3  Bülent   Kocaeli
4  İlknur     Sivas
5   Harun     Konya

In [166]:
# Son satıra ekleme yapmak için -1 kullanamayız sebebi Pandas'ta Series ve Dataframe'de index bölümüne yazılan şey ne ise çıktı olarak onu görürüz.

In [167]:
df.loc[-1] = ["Son","Satır"]

In [168]:
df

ad     şehir
 0    Aziz  İstanbul
 1  Mehmet   Denizli
 2    Nadi     Bursa
 3  Bülent   Kocaeli
 4  İlknur     Sivas
 5   Harun     Konya
-1     Son     Satır

In [169]:
df.loc["Ayşe"] = ["Son","Sütun"]

In [170]:
df

ad     şehir
0       Aziz  İstanbul
1     Mehmet   Denizli
2       Nadi     Bursa
3     Bülent   Kocaeli
4     İlknur     Sivas
5      Harun     Konya
-1       Son     Satır
Ayşe     Son     Sütun

In [171]:
# Son satıra ekleme yapmak için dataframe'in uzunluğunu alacağız.

In [174]:
df.loc[len(df)] = ["Yeni","Kayıt"] # sona koyacağımız index, indexler sıfırdan başladığı için dataframe'in eleman sayısına eşittir.

In [175]:
df

ad     şehir
0       Aziz  İstanbul
1     Mehmet   Denizli
2       Nadi     Bursa
3     Bülent   Kocaeli
4     İlknur     Sivas
5      Harun     Konya
-1       Son     Satır
Ayşe     Son     Sütun
8       Yeni     Kayıt
9       Yeni     Kayıt

In [178]:
#Df'de delete yapma
df["Maas"] = 500 # kolon ekledik, bu kolonu sileceğiz.

In [179]:
df

ad     şehir  Maas
0       Aziz  İstanbul   500
1     Mehmet   Denizli   500
2       Nadi     Bursa   500
3     Bülent   Kocaeli   500
4     İlknur     Sivas   500
5      Harun     Konya   500
-1       Son     Satır   500
Ayşe     Son     Sütun   500
8       Yeni     Kayıt   500
9       Yeni     Kayıt   500

In [180]:
df.drop("Maas",axis=1) # axis = 0 yatayı, axis = 1 dikeyi ifade eder.

ad     şehir
0       Aziz  İstanbul
1     Mehmet   Denizli
2       Nadi     Bursa
3     Bülent   Kocaeli
4     İlknur     Sivas
5      Harun     Konya
-1       Son     Satır
Ayşe     Son     Sütun
8       Yeni     Kayıt
9       Yeni     Kayıt

In [181]:
# Yukarıdaki işlemde çıktıda sildiğini gördük ama dataframe'de bu şekilde silinmez. Dataframe'de silinmesi için inplace = True demeliyiz.

In [182]:
df.drop("Maas",axis=1, inplace=True)

In [183]:
df

ad     şehir
0       Aziz  İstanbul
1     Mehmet   Denizli
2       Nadi     Bursa
3     Bülent   Kocaeli
4     İlknur     Sivas
5      Harun     Konya
-1       Son     Satır
Ayşe     Son     Sütun
8       Yeni     Kayıt
9       Yeni     Kayıt

In [187]:
df.drop(1,axis=0, inplace=True) #Satır silme

In [188]:
df

ad     şehir
0       Aziz  İstanbul
3     Bülent   Kocaeli
4     İlknur     Sivas
5      Harun     Konya
-1       Son     Satır
Ayşe     Son     Sütun
8       Yeni     Kayıt
9       Yeni     Kayıt

In [1]:
#Merge --> Elimizde iki veya daha fazla df varsa bu iki veri kaynağını alt alta birleştirebiliriz.
#Bunu yapmak için SQL'deki Join mantığını bilmemiz gerekir.

In [2]:
# Merge - Join

import pandas as pd

df_calisanlar = pd.DataFrame({
    "Calisan_ID": [101, 102, 103, 104],
    "Ad": ["Ali", "Veli", "Ayşe", "Fatma"],
    "BolumID": ["1", "1", "5", "3"]
})

df_bolumler = pd.DataFrame({
    "BolumID": ["1", "2", "3", "4"],
    "Bolum": ["IT", "HR", "Finance", "Legal"]
})

In [3]:
merge_inner = pd.merge(df_calisanlar, df_bolumler, on="BolumID",how="inner")

In [5]:
merge_inner # inner --> iki tablodada olma zorunluluğu var demektir, BolumID iki tarafta da olan 1 ve 3 değerleridir.

Calisan_ID     Ad BolumID    Bolum
0         101    Ali       1       IT
1         102   Veli       1       IT
2         104  Fatma       3  Finance

In [6]:
merge_left = pd.merge(df_calisanlar, df_bolumler, on="BolumID",how="left")

In [8]:
merge_left # çalışanlar tablosu olduğu gibi geldi. Sağdaki tablodan da bulabildiği kadar getirdi.

Calisan_ID     Ad BolumID    Bolum
0         101    Ali       1       IT
1         102   Veli       1       IT
2         103   Ayşe       5      NaN
3         104  Fatma       3  Finance

In [9]:
merge_right = pd.merge(df_calisanlar, df_bolumler, on="BolumID",how="right")

In [10]:
merge_right

Calisan_ID     Ad BolumID    Bolum
0       101.0    Ali       1       IT
1       102.0   Veli       1       IT
2         NaN    NaN       2       HR
3       104.0  Fatma       3  Finance
4         NaN    NaN       4    Legal

In [11]:
# Concat --> SQL'de Union olarak bilinir. Verileri alt alta birleştirir.

In [13]:
df1 = pd.DataFrame({"Sira": [1, 2, 3]})
df2 = pd.DataFrame({"Sira": [4, 5, 6]})

In [14]:
df1

Sira
0     1
1     2
2     3

In [15]:
df2

Sira
0     4
1     5
2     6

In [18]:
pd.concat([df1,df2]) #Dikeyde birleştirir.

Sira
0     1
1     2
2     3
0     4
1     5
2     6

In [19]:
pd.concat([df1,df2], axis=1) #Yatayda birleştirir.

Sira  Sira
0     1     4
1     2     5
2     3     6

In [20]:
#Dikeyde birleştirem fakat indexleri sıfırlama
pd.concat([df1,df2], axis=0, ignore_index=True)

Sira
0     1
1     2
2     3
3     4
4     5
5     6